### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by jonschlinkert** [generate/generate#35]
I'd like to see the following on a formal roadmap (feedback, suggestions, ideas, requests, are all very welcome!):

- [ ] **improve prompts**: This is a top priority. Node.js needs a fast, pluggable prompt library that isn't bloated and dog slow. We might have some ideas here :)
- [ ] **persisted data** this needs to be easier and more consistent. Generate broke new ground by supporting chained generators (which means you can run multiple generators in a row from the command line, resulting in an experience that feels like one generator). While awesome, it introduces challenges regarding how data and state are managed from one generator to the next during prompts. Each generator has it's own instance of generate, along with it's own options, data, and so on. Generate also exposes a special "base" instance, on the `app.base` property, which can be used (at your own risk) for shared data. Since we're scaffolding out projects, and not serving web pages, this is a really nice solution.  But we still have some rough edges around how "hints" are displayed and answers are pre-populated from successive prompts from multiple generators. 
- [ ] **docs**: we know this is a problem with verb, assemble and generate, but we're working on docs for all three and will be releasing them soon, along with new websites and resources for finding plugins, and more

TBC...

**Comment by jamen** [comment]
I like how `generate`'s generators share an environment.  In fact, I initially added the ability to [run multiple generators with yo](https://github.com/yeoman/yo/pull/414) under the same environment; however, they [didn't like the idea of having them share data](https://github.com/yeoman/environment/pull/56) on that environment (for justifiable reasons).  I think at the very least it is useful for sub-generators and composing them together.   So to me, that is one of the strong points of generate, because in my eyes it allows for more powerful composability (simpler prompting that scaffolds better and more normalized projects)

To give you an example of a place I wanted to use this in, I was going to make this "generator suite" for yeoman that scaffolded out multiple types of projects (called [`generator-devjs`](https://github.com/jamen/generator-devjs)) using sub-generators that share a `global.devjs`...  so the main idea was that it only prompted once for certain information then reused it in the other sub-generators.  That generator has since been discontinued because I've been content enough with generate's packages, though.

**Comment by jonschlinkert** [comment]
awesome! yeah we plan to expand on how generators share data. This is also a favorite feature of mine because of how intuitive it is (to reiterate for anyone who might be joining the convo, every generator is created with a new instance of generate, but we also expose a special "shared" instance that can be used to pass specific data or options back between generators).

**Comment by tunnckoCore** [comment]
> Node.js needs a fast, pluggable prompt library that isn't bloated and dog slow. We might have some ideas here :)

Sounds great! `keypress` looks good as starting point for this job. I have some very old shit thingy with it https://github.com/tunnckoCore/prompt-promise. Let me know if can help or suggest something more - the word "pluggable" is enough. 

Let's do it.

**Comment by jonschlinkert** [comment]
K you ready for this? :) I think we can simplify further, but it's just a start.

**Comment by jonschlinkert** [comment]
progress here: https://github.com/enquirer

**Comment by tunnckoCore** [comment]
awesome! i'll look.

**Comment by jonschlinkert** [comment]
@tunnckoCore can you check gitter? I left a msg

**Comment by tunnckoCore** [comment]
Yea, no problem. I'm on slack rooms of toolkit too. :)

**Comment by jonschlinkert** [comment]
I didn't know toolkit had one lol. I do now!

**Comment by jonschlinkert** [comment]
I just commented there

**Comment by tunnckoCore** [comment]
> I didn't know toolkit had one lol. I do now!

Yea, I don't see you there https://[generatejs/basejs/verbjs/etc].slack.com/messages/general :)

**Comment by jonschlinkert** [comment]
you don't? I should be. I thought you meant an actual `toolkit` room.
